package com.locker.domain.backup

import com.google.gson.Gson
import com.locker.data.db.CategoryBrandCrossRef
import com.locker.data.db.CategoryEntity
import com.locker.data.db.LockerDao
import com.locker.data.db.LockerItem
import kotlinx.coroutines.flow.first

object BackupManager {
    private val gson = Gson()

    /**
     * Serializes all vault data into a JSON string.
     */
    suspend fun createBackupPayload(dao: LockerDao): String {
        val items = dao.getAllItems().first()
        val categories = dao.getAllCategories().first()
        
        // Fetch all cross-refs
        // Note: Room flow returns list per category, so we need a manual query to get all cross refs.
        // Wait, we don't have a get all cross-refs query. Let's just fetch them per category.
        val crossRefs = mutableListOf<CategoryBrandCrossRef>()
        categories.forEach { cat ->
            val brands = dao.getBrandsForCategory(cat.name).first()
            brands.forEach { brandId ->
                crossRefs.add(CategoryBrandCrossRef(cat.name, brandId))
            }
        }

        val payload = BackupPayload(
            version = 1,
            items = items,
            categories = categories,
            categoryBrands = crossRefs
        )
        return gson.toJson(payload)
    }

    /**
     * Parses the decrypted JSON and inserts it into the database, skipping duplicates.
     * Returns a Pair of (Items Inserted, Items Skipped).
     */
    suspend fun restoreFromPayload(jsonPayload: String, dao: LockerDao): Pair<Int, Int> {
        val payload = try {
            gson.fromJson(jsonPayload, BackupPayload::class.java)
        } catch (e: Exception) {
            throw IllegalArgumentException("Invalid backup format")
        }

        var inserted = 0
        var skipped = 0

        // 1. Restore Categories (IGNORE strategy handles duplicates)
        payload.categories.forEach { cat ->
            dao.insertCategory(cat)
        }

        // 2. Restore Category-Brand mappings
        payload.categoryBrands.forEach { crossRef ->
            dao.insertCategoryBrandCrossRef(crossRef)
        }

        // 3. Restore Items (Skip duplicates based on title and username)
        val existingItems = dao.getAllItems().first()
        payload.items.forEach { importedItem ->
            val isDuplicate = existingItems.any {
                it.title.equals(importedItem.title, ignoreCase = true) &&
                it.username.equals(importedItem.username, ignoreCase = true)
            }
            if (isDuplicate) {
                skipped++
            } else {
                // Insert as a new item (ID will be autogenerated if we reset it to 0, 
                // but importedItem has its old ID. Room with REPLACE might overwrite if ID matches.
                // We should ensure we insert it as a *new* row to avoid overwriting unrelated items.
                dao.insertItem(
                    LockerItem(
                        id = 0, // Force auto-generate
                        title = importedItem.title,
                        username = importedItem.username,
                        secretValue = importedItem.secretValue,
                        category = importedItem.category,
                        websiteUrl = importedItem.websiteUrl ?: "",
                        notes = importedItem.notes ?: "",
                        timestamp = importedItem.timestamp
                    )
                )
                inserted++
            }
        }

        return Pair(inserted, skipped)
    }
}
